kruskal:	mstree.o kruskal.o
	g++ -o kruskal mstree.o kruskal.o
prim:		mstree.o prim.o
	g++ -o prim mstree.o prim.o
sollin:		mstree.o sollin.o
	g++ -o sollin mstree.o sollin.o
kruskal.o prim.o sollin.o mstree.o:	mstree.h
