hw5a: hw5.o evala.o post.o
	g++ -o hw5a hw5.o evala.o post.o
hw5b: hw5.o evalb.o post.o
	g++ -o hw5b hw5.o evalb.o post.o

hw4: hw4.o post.o
	g++ -o hw4 hw4.o post.o
hw4.o hw5.o post.o evla.o evalb.o post.o : post.h
